AllCops:
  TargetRubyVersion: 2.7

  NewCops: enable

  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/*'
    - 'config/initializers/*'

Metrics/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 50

Metrics/ClassLength:
  Max: 160

Metrics/AbcSize:
  Max: 80

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
